version: '3.7'
services:
  mysql-db:
    image: 'mysql:5.6'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
    ports:
      - '3306:3306'
  spring-app:
    build:
      context: .
    container_name: spring-app
    image: haj123er/hajer123
    ports:
      - '8083:8083'
    depends_on:
      - mysql-db
volumes:
  dbvol: